// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpdhcesneddslwauqyzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwZGhjZXNuZWRkc2x3YXVxeXp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NTgzMjksImV4cCI6MjA2NjQzNDMyOX0.NCdJpE-R-JY62c2gdRCcShn07eM8DWqLem79_RCq1nQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);